info:
  project:
    name: Initializr for Spring Cloud Stream (SCS)
    version: 0.4.0
  # remember to update static/install.sh as well:
  spring-boot:
    version: 1.3.3.RELEASE

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048

initializr:
  env:
    boms:
      spring-cloud-stream-bom:
        groupId: org.springframework.cloud.stream.app
        artifactId: spring-cloud-stream-app-dependencies
        version: 1.0.0.BUILD-SNAPSHOT
        repositories: spring-snapshots,spring-milestones
      vaadin-bom:
        groupId: com.vaadin
        artifactId: vaadin-bom
        version: 7.6.3
      cloud-bom:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-dependencies
        mappings:
          - versionRange: "[1.2.3.RELEASE,1.3.0.M1)"
            version: Angel.SR6
          - versionRange: "[1.3.0.M2,1.3.2.RELEASE]"
            version: Brixton.M5
            repositories: spring-snapshots,spring-milestones
          - versionRange: 1.3.3.BUILD-SNAPSHOT
            version: Brixton.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      cloud-dataflow-bom:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-dataflow-dependencies
        version: 1.0.0.BUILD-SNAPSHOT
        additionalBoms: [cloud-bom]
        repositories: spring-snapshots,spring-milestones
    kotlin:
      version: 1.0.0
  dependencies:
    - name: SCS Starter Module
      content:
        - name: File Source
          id: spring-cloud-starter-stream-source-file
          description: File Source Starter
          groupId: org.springframework.cloud.stream.app
          artifactId: spring-cloud-starter-stream-source-file
          scope: compile
          starter: true
          bom: spring-cloud-stream-bom
        - name: File Sink
          id: spring-cloud-starter-stream-sink-file
          description: File Sink Starter
          groupId: org.springframework.cloud.stream.app
          artifactId: spring-cloud-starter-stream-sink-file
          scope: compile
          starter: true
          bom: spring-cloud-stream-bom
        - name: HTTP Source
          id: spring-cloud-starter-stream-source-http
          description: HTTP Source Starter
          groupId: org.springframework.cloud.stream.app
          artifactId: spring-cloud-starter-stream-source-http
          scope: compile
          starter: true
          bom: spring-cloud-stream-bom
        - name: Log Sink
          id: spring-cloud-starter-stream-sink-log
          description: Log Sink Starter
          groupId: org.springframework.cloud.stream.app
          artifactId: spring-cloud-starter-stream-sink-log
          scope: compile
          starter: true
          bom: spring-cloud-stream-bom
        - name: Time Source
          id: spring-cloud-starter-stream-source-time
          description: Time Source Starter
          groupId: org.springframework.cloud.stream.app
          artifactId: spring-cloud-starter-stream-source-time
          scope: compile
          starter: true
          bom: spring-cloud-stream-bom
    - name: Binder Type
      content:
        - name: Kafka binder
          id: spring-cloud-stream-binder-kafka
          description: Kafka binder implementation
          groupId: org.springframework.cloud
          artifactId: spring-cloud-stream-binder-kafka
          scope: compile
          starter: false
        - name: Rabbit binder
          id: spring-cloud-stream-binder-rabbit
          description: Rabbit binder implementation
          groupId: org.springframework.cloud
          artifactId: spring-cloud-stream-binder-rabbit
          scope: compile
          starter: false
        - name: Redis binder
          id: spring-cloud-stream-binder-redis
          description: Redis binder implementation
          groupId: org.springframework.cloud
          artifactId: spring-cloud-stream-binder-redis
          scope: compile
          starter: false
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 1.8
      default: true
    - id: 1.7
      default: false
    - id: 1.6
      default: false
  languages:
    - name: Java
      id: java
      default: true
    - name: Groovy
      id: groovy
      default: false
    - name: Kotlin
      id: kotlin
      default: false
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false
